---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - //home/shuai/jellyfin:/config
      - /home/shuai/jellyfin/tv:/data/tvshows
      - /var/www/html/downloads:/data/movies
    ports:
      - 8096:8096
    restart: unless-stoppedv